/* NovaX 3D conveyor hero background. Subtle + mobile-optimized. Renders into #nv3dbg inside .hero. Additive: does not touch any site feature. */
(function(){
  var cvs=document.getElementById('nv3dbg'); if(!cvs||!window.THREE) return;
  var host=cvs.parentElement||document.body;
  var isTouch=(window.matchMedia&&window.matchMedia('(pointer:coarse)').matches)||window.innerWidth<820;
  var lowMo=(window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches);
  var renderer; try{ renderer=new THREE.WebGLRenderer({canvas:cvs,antialias:!isTouch,alpha:true,powerPreference:isTouch?'low-power':'high-performance'}); }catch(e){ return; }
  renderer.setPixelRatio(isTouch?Math.min(window.devicePixelRatio||1,0.9):Math.min(window.devicePixelRatio||1,1.8));
  if(THREE.sRGBEncoding!==undefined) renderer.outputEncoding=THREE.sRGBEncoding;
  if(THREE.ACESFilmicToneMapping!==undefined){ renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=0.92; }
  renderer.shadowMap.enabled=!isTouch; renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  function W(){ return Math.max(1,window.innerWidth); }
  function H(){ return Math.max(1,window.innerHeight); }
  renderer.setSize(W(),H(),false);
  var scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x041610, isTouch?0.02:0.015);
  var camera=new THREE.PerspectiveCamera(52,W()/H(),0.1,500);
  var camBase=new THREE.Vector3(8,6.5,24);
  function frame(){ var a=W()/H(); camera.aspect=a; if(a<0.8){camera.fov=66;camBase.set(3.5,8,32);}else if(a<1.4){camera.fov=58;camBase.set(6,7.2,28);}else{camera.fov=50;camBase.set(8,6.5,24);} camera.updateProjectionMatrix(); }
  frame(); camera.position.copy(camBase);
  scene.add(new THREE.HemisphereLight(0x8ff0cf,0x05140e,0.5));
  var key=new THREE.DirectionalLight(0xffeccb,1.25); key.position.set(12,24,14); key.castShadow=!isTouch;
  if(!isTouch){ key.shadow.mapSize.set(1024,1024); key.shadow.camera.near=1; key.shadow.camera.far=80; key.shadow.camera.left=-20; key.shadow.camera.right=20; key.shadow.camera.top=20; key.shadow.camera.bottom=-20; key.shadow.bias=-0.0004; }
  scene.add(key);
  var teal=new THREE.PointLight(0x14c77b,0.8,140); teal.position.set(-12,9,6); scene.add(teal);
  var rim=new THREE.PointLight(0x0bd3a0,0.7,160); rim.position.set(8,6,-46); scene.add(rim);
  var NEAR=26, FAR=isTouch?-85:-160, RANGE=NEAR-FAR, BW=7;
  function wrap(z){ var v=((z-FAR)%RANGE+RANGE)%RANGE; return FAR+v; }
  function glow(size,op){ var c=document.createElement('canvas'); c.width=c.height=128; var g=c.getContext('2d'); var gr=g.createRadialGradient(64,64,0,64,64,64); gr.addColorStop(0,'rgba(20,199,123,'+op+')'); gr.addColorStop(0.5,'rgba(20,199,123,'+(op*0.35)+')'); gr.addColorStop(1,'rgba(0,0,0,0)'); g.fillStyle=gr; g.fillRect(0,0,128,128); var t=new THREE.CanvasTexture(c); var s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,blending:THREE.AdditiveBlending,transparent:true,depthWrite:false})); s.scale.set(size,size,1); return s; }
  var floor=new THREE.Mesh(new THREE.PlaneGeometry(260,500),new THREE.MeshStandardMaterial({color:0x06130e,roughness:0.96,metalness:0.1})); floor.rotation.x=-Math.PI/2; floor.position.y=-1.7; floor.receiveShadow=!isTouch; scene.add(floor);
  var belt=new THREE.Mesh(new THREE.BoxGeometry(BW,0.5,RANGE+70),new THREE.MeshStandardMaterial({color:0x121212,roughness:0.82,metalness:0.32})); belt.position.set(0,-0.25,(NEAR+FAR)/2); belt.receiveShadow=!isTouch; scene.add(belt);
  var railMat=new THREE.MeshStandardMaterial({color:0x2c332f,roughness:0.45,metalness:0.8});
  [-1,1].forEach(function(s){ var r=new THREE.Mesh(new THREE.BoxGeometry(0.5,1.2,RANGE+70),railMat); r.position.set(s*(BW/2+0.25),0.1,(NEAR+FAR)/2); r.castShadow=!isTouch; r.receiveShadow=!isTouch; scene.add(r); var trim=new THREE.Mesh(new THREE.BoxGeometry(0.1,0.1,RANGE+70),new THREE.MeshStandardMaterial({color:0x0b2a1f,emissive:0x14c77b,emissiveIntensity:0.55})); trim.position.set(s*(BW/2+0.25),0.72,(NEAR+FAR)/2); scene.add(trim); });
  for(var lz=NEAR-6; lz>FAR; lz-=18){ [-1,1].forEach(function(s){ var leg=new THREE.Mesh(new THREE.BoxGeometry(0.4,1.5,0.4),railMat); leg.position.set(s*(BW/2+0.15),-1.0,lz); leg.castShadow=!isTouch; scene.add(leg); }); }
  var movers=[]; var slatMat=new THREE.MeshStandardMaterial({color:0x1c1c1c,roughness:0.68,metalness:0.38}); var slatGeo=new THREE.BoxGeometry(BW-0.5,0.14,0.5); var rollerMat=new THREE.MeshStandardMaterial({color:0x3a423d,roughness:0.4,metalness:0.85}); var rollerGeo=new THREE.CylinderGeometry(0.26,0.26,BW-0.4,12); var i2=0; var slatStep=isTouch?2.8:1.1;
  for(var z=NEAR; z>FAR; z-=slatStep){ var sl=new THREE.Mesh(slatGeo,slatMat); sl.position.set(0,0.06,z); sl.receiveShadow=!isTouch; scene.add(sl); movers.push({m:sl,bz:z}); if(!isTouch&&i2%3===0){ var ro=new THREE.Mesh(rollerGeo,rollerMat); ro.rotation.z=Math.PI/2; ro.position.set(0,-0.05,z); scene.add(ro); movers.push({m:ro,bz:z}); } i2++; }
  function rr(g,x,y,w,h,r){ g.beginPath(); g.moveTo(x+r,y); g.arcTo(x+w,y,x+w,y+h,r); g.arcTo(x+w,y+h,x,y+h,r); g.arcTo(x,y+h,x,y,r); g.arcTo(x,y,x+w,y,r); g.closePath(); }
  function kraft(g){ var gr=g.createLinearGradient(0,0,512,512); gr.addColorStop(0,'#d2a667'); gr.addColorStop(1,'#b6864a'); g.fillStyle=gr; g.fillRect(0,0,512,512); g.strokeStyle='rgba(120,85,40,.13)'; g.lineWidth=2; for(var i=0;i<512;i+=10){ g.beginPath(); g.moveTo(0,i); g.lineTo(512,i); g.stroke(); } g.fillStyle='rgba(90,60,25,.18)'; g.fillRect(248,0,16,512); }
  function label(g){ g.fillStyle='#ffffff'; rr(g,40,250,432,198,16); g.fill(); g.fillStyle='#0b2a1f'; rr(g,60,270,86,68,12); g.fill(); g.fillStyle='#14c77b'; rr(g,73,283,60,42,8); g.fill(); g.fillStyle='#04130d'; g.textBaseline='middle'; g.font='900 32px Inter, Arial'; g.fillText('NX',84,305); g.fillStyle='#0b2a1f'; g.font='800 50px Inter, Arial'; g.fillText('NovaX',168,298); g.fillStyle='#6b7d74'; g.font='600 19px Inter, Arial'; g.fillText('LOGISTICS - COD',170,334); g.strokeStyle='#b53a2c'; g.lineWidth=4; rr(g,332,260,116,46,10); g.stroke(); g.fillStyle='#b53a2c'; g.font='800 24px Inter, Arial'; g.fillText('COD',354,284); g.fillStyle='#161616'; var bx=70; for(var b=0;b<60;b++){ var w=1+Math.round(Math.random()*4); g.fillRect(bx,376,w,56); bx+=w+2+Math.round(Math.random()*3); if(bx>444)break; } }
  function tape(g){ g.fillStyle='rgba(20,199,123,.78)'; g.fillRect(0,150,512,60); g.fillRect(226,0,60,512); g.fillStyle='rgba(255,255,255,.85)'; g.font='800 21px Inter, Arial'; g.textBaseline='middle'; for(var k=20;k<512;k+=120){ g.fillText('NovaX',k,180); } }
  function tex(kind){ var c=document.createElement('canvas'); c.width=512;c.height=512; var g=c.getContext('2d'); kraft(g); if(kind===0){ tape(g); label(g); } else if(kind===1){ g.fillStyle='rgba(228,208,150,.5)'; g.fillRect(0,150,512,58); label(g); g.save(); g.translate(256,256); g.rotate(-0.35); g.strokeStyle='#b53a2c'; g.lineWidth=7; rr(g,-200,150,400,66,12); g.stroke(); g.fillStyle='#b53a2c'; g.font='900 44px Inter, Arial'; g.textAlign='center'; g.textBaseline='middle'; g.fillText('FRAGILE',0,184); g.restore(); g.textAlign='left'; } else { tape(g); g.fillStyle='#0b2a1f'; g.textBaseline='middle'; g.font='900 62px Inter, Arial'; g.fillText('NovaX',60,300); g.fillStyle='#6b7d74'; g.font='700 23px Inter, Arial'; g.fillText('HANDLE WITH CARE',62,346); } var t=new THREE.CanvasTexture(c); t.anisotropy=isTouch?2:4; if(THREE.sRGBEncoding!==undefined) t.encoding=THREE.sRGBEncoding; return t; }
  var mats=[tex(0),tex(1),tex(2)].map(function(t){ return new THREE.MeshStandardMaterial({map:t,roughness:0.85,metalness:0.04}); });
  var parcels=[]; var idx=0; var pStep=isTouch?14:7.5;
  for(var z=NEAR-3; z>FAR+4; z-=pStep){ var w=1.8+Math.random()*1.0,h=1.3+Math.random()*0.8,d=1.3+Math.random()*0.7; var box=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mats[idx%mats.length]); box.castShadow=!isTouch; box.receiveShadow=!isTouch; box.position.set((idx%2?-1:1)*(0.4+Math.random()*0.9),h/2,z); box.rotation.y=(Math.random()-0.5)*0.4; scene.add(box); parcels.push({m:box,bz:z,h:h,sway:Math.random()*6}); idx++; if(!isTouch&&Math.random()<0.3){ var sw=w*0.6; var sb=new THREE.Mesh(new THREE.BoxGeometry(sw,sw*0.7,d*0.6),mats[(idx+1)%mats.length]); sb.castShadow=true; var sy=h+sw*0.35; sb.position.set(box.position.x*0.6,sy,z); sb.rotation.y=Math.random(); scene.add(sb); parcels.push({m:sb,bz:z,h:h,sway:Math.random()*6,off:sy}); } }
  var gateZ=-1, gate=new THREE.Group(); scene.add(gate); var postMat=new THREE.MeshStandardMaterial({color:0x10201a,roughness:0.45,metalness:0.8});
  [-1,1].forEach(function(s){ var p=new THREE.Mesh(new THREE.BoxGeometry(0.5,6,0.7),postMat); p.position.set(s*(BW/2+0.3),3,gateZ); p.castShadow=!isTouch; gate.add(p); });
  var topbar=new THREE.Mesh(new THREE.BoxGeometry(BW+1.6,0.9,0.8),postMat); topbar.position.set(0,5.8,gateZ); topbar.castShadow=!isTouch; gate.add(topbar);
  (function(){ var c=document.createElement('canvas'); c.width=512;c.height=96; var g=c.getContext('2d'); g.fillStyle='#0b2a1f'; g.fillRect(0,0,512,96); g.fillStyle='#14c77b'; g.fillRect(0,0,8,96); g.fillStyle='#eafff5'; g.textBaseline='middle'; g.font='800 44px Inter, Arial'; g.fillText('NovaX',26,50); g.fillStyle='#7ef7c9'; g.font='700 28px Inter, Arial'; g.fillText('SCAN GATE',210,52); var t=new THREE.CanvasTexture(c); var pl=new THREE.Mesh(new THREE.PlaneGeometry(BW+1.4,0.78),new THREE.MeshBasicMaterial({map:t,transparent:true})); pl.position.set(0,5.8,gateZ+0.42); gate.add(pl); })();
  var trimBar=new THREE.Mesh(new THREE.BoxGeometry(BW+1.2,0.1,0.1),new THREE.MeshStandardMaterial({color:0x0b2a1f,emissive:0x14c77b,emissiveIntensity:0.7})); trimBar.position.set(0,5.25,gateZ+0.45); gate.add(trimBar);
  var beam=new THREE.Mesh(new THREE.PlaneGeometry(BW,5),new THREE.MeshBasicMaterial({color:0x14c77b,transparent:true,opacity:0.05,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false})); beam.position.set(0,2.6,gateZ); gate.add(beam);
  var scanLine=new THREE.Mesh(new THREE.BoxGeometry(BW,0.1,0.05),new THREE.MeshBasicMaterial({color:0x7ef7c9,blending:THREE.AdditiveBlending,transparent:true,opacity:0.8,depthWrite:false})); gate.add(scanLine);
  var gateGlow=glow(5,0.5); gateGlow.position.set(0,3,gateZ); gate.add(gateGlow);
  var dustCount=isTouch?26:230, dg=new THREE.BufferGeometry(), dv=[]; for(var i=0;i<dustCount;i++){ dv.push((Math.random()-0.5)*BW,Math.random()*6,gateZ+(Math.random()-0.5)*40); } dg.setAttribute('position',new THREE.Float32BufferAttribute(dv,3)); var dust=new THREE.Points(dg,new THREE.PointsMaterial({color:0xbfffe6,size:0.05,transparent:true,opacity:0.35,blending:THREE.AdditiveBlending,depthWrite:false})); scene.add(dust);
  var starCount=isTouch?100:520, sg=new THREE.BufferGeometry(), sv=[]; for(var i=0;i<starCount;i++){ sv.push((Math.random()-0.5)*240,Math.random()*80+8,(Math.random()-0.5)*280); } sg.setAttribute('position',new THREE.Float32BufferAttribute(sv,3)); scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0x9fe9c8,size:0.12,transparent:true,opacity:0.28})));
  var mx=0,my=0; if(!isTouch){ window.addEventListener('mousemove',function(e){ mx=(e.clientX/window.innerWidth-0.5); my=(e.clientY/window.innerHeight-0.5); }); }
  var scrollP=0; function onScroll(){ var max=(document.documentElement.scrollHeight-window.innerHeight)||1; scrollP=Math.max(0,Math.min(1,(window.pageYOffset||window.scrollY||0)/max)); } window.addEventListener('scroll',onScroll,{passive:true}); onScroll();
  var rT; window.addEventListener('resize',function(){ clearTimeout(rT); rT=setTimeout(function(){ renderer.setSize(W(),H(),false); frame(); },150); });
  var vis=true; /* full-page fixed canvas: always visible while tab is active (pauses on document.hidden) */
  var clock=new THREE.Clock(); var __last=-1, __minDt=isTouch?0.033:0;
  function animate(){ requestAnimationFrame(animate); if(document.hidden||!vis) return; var t=clock.getElapsedTime(); if(__minDt&&(t-__last)<__minDt) return; __last=t; var flow=(lowMo?0:t*1.6)+scrollP*RANGE*1.1; movers.forEach(function(s){ s.m.position.z=wrap(s.bz+flow); }); parcels.forEach(function(p){ p.m.position.z=wrap(p.bz+flow); var base=(p.off!==undefined)?p.off:p.h/2; p.m.position.y=base+Math.sin(t*1.6+p.sway)*0.02; }); var sweep=2.6+Math.sin(t*1.5)*2.0; scanLine.position.set(0,sweep,gateZ); beam.material.opacity=0.04+Math.abs(Math.sin(t*1.5))*0.07; gateGlow.material.opacity=0.4+Math.sin(t*2.2)*0.14; camera.position.x+=((camBase.x+mx*4)-camera.position.x)*0.045; camera.position.y+=((camBase.y-my*2)-camera.position.y)*0.045; camera.position.z+=(camBase.z-camera.position.z)*0.045; camera.lookAt(0,1.6,-12); dust.rotation.y=t*0.015; renderer.render(scene,camera); }
  animate();
})();
