-- NovaX Sales: the rep guide PDF, served only to signed-in reps and admins
-- (2 Oct 2026). Not a site file: everything in the repo is public on
-- novaxlogistics.com, and the guide is for reps only. Replace the file by
-- re-running the upsert generated by scripts (see sales_files below).
begin;
create table if not exists public.sales_files (
  name text primary key,
  mime text not null,
  content bytea not null,
  updated_at timestamptz not null default now()
);
alter table public.sales_files enable row level security;
revoke all on public.sales_files from public, anon, authenticated;

create or replace function public.sales_guide()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if public.sales_current_rep() is null and not public.is_admin() then
    raise exception 'This page is for NovaX sales reps. Ask NovaX to add you.' using errcode = '42501';
  end if;
  return (select jsonb_build_object('name', 'NovaX-Sales-Rep-Guide.pdf', 'mime', f.mime, 'updated_at', f.updated_at,
                                    'b64', translate(encode(f.content, 'base64'), E'\n', ''))
          from public.sales_files f where f.name = 'rep-guide');
end $$;
revoke all on function public.sales_guide() from public, anon, authenticated;
grant execute on function public.sales_guide() to authenticated;
commit;
